/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: login.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "login.pb-c.h"
void   netmsg__empty_msg__init
                     (Netmsg__EmptyMsg         *message)
{
  static const Netmsg__EmptyMsg init_value = NETMSG__EMPTY_MSG__INIT;
  *message = init_value;
}
size_t netmsg__empty_msg__get_packed_size
                     (const Netmsg__EmptyMsg *message)
{
  assert(message->base.descriptor == &netmsg__empty_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t netmsg__empty_msg__pack
                     (const Netmsg__EmptyMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &netmsg__empty_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t netmsg__empty_msg__pack_to_buffer
                     (const Netmsg__EmptyMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &netmsg__empty_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Netmsg__EmptyMsg *
       netmsg__empty_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Netmsg__EmptyMsg *)
     protobuf_c_message_unpack (&netmsg__empty_msg__descriptor,
                                allocator, len, data);
}
void   netmsg__empty_msg__free_unpacked
                     (Netmsg__EmptyMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &netmsg__empty_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   netmsg__ping_pong__init
                     (Netmsg__PingPong         *message)
{
  static const Netmsg__PingPong init_value = NETMSG__PING_PONG__INIT;
  *message = init_value;
}
size_t netmsg__ping_pong__get_packed_size
                     (const Netmsg__PingPong *message)
{
  assert(message->base.descriptor == &netmsg__ping_pong__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t netmsg__ping_pong__pack
                     (const Netmsg__PingPong *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &netmsg__ping_pong__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t netmsg__ping_pong__pack_to_buffer
                     (const Netmsg__PingPong *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &netmsg__ping_pong__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Netmsg__PingPong *
       netmsg__ping_pong__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Netmsg__PingPong *)
     protobuf_c_message_unpack (&netmsg__ping_pong__descriptor,
                                allocator, len, data);
}
void   netmsg__ping_pong__free_unpacked
                     (Netmsg__PingPong *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &netmsg__ping_pong__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   netmsg__req_login__init
                     (Netmsg__ReqLogin         *message)
{
  static const Netmsg__ReqLogin init_value = NETMSG__REQ_LOGIN__INIT;
  *message = init_value;
}
size_t netmsg__req_login__get_packed_size
                     (const Netmsg__ReqLogin *message)
{
  assert(message->base.descriptor == &netmsg__req_login__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t netmsg__req_login__pack
                     (const Netmsg__ReqLogin *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &netmsg__req_login__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t netmsg__req_login__pack_to_buffer
                     (const Netmsg__ReqLogin *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &netmsg__req_login__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Netmsg__ReqLogin *
       netmsg__req_login__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Netmsg__ReqLogin *)
     protobuf_c_message_unpack (&netmsg__req_login__descriptor,
                                allocator, len, data);
}
void   netmsg__req_login__free_unpacked
                     (Netmsg__ReqLogin *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &netmsg__req_login__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define netmsg__empty_msg__field_descriptors NULL
#define netmsg__empty_msg__field_indices_by_name NULL
#define netmsg__empty_msg__number_ranges NULL
const ProtobufCMessageDescriptor netmsg__empty_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "netmsg.EmptyMsg",
  "EmptyMsg",
  "Netmsg__EmptyMsg",
  "netmsg",
  sizeof(Netmsg__EmptyMsg),
  0,
  netmsg__empty_msg__field_descriptors,
  netmsg__empty_msg__field_indices_by_name,
  0,  netmsg__empty_msg__number_ranges,
  (ProtobufCMessageInit) netmsg__empty_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor netmsg__ping_pong__field_descriptors[1] =
{
  {
    "time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Netmsg__PingPong, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned netmsg__ping_pong__field_indices_by_name[] = {
  0,   /* field[0] = time */
};
static const ProtobufCIntRange netmsg__ping_pong__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor netmsg__ping_pong__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "netmsg.PingPong",
  "PingPong",
  "Netmsg__PingPong",
  "netmsg",
  sizeof(Netmsg__PingPong),
  1,
  netmsg__ping_pong__field_descriptors,
  netmsg__ping_pong__field_indices_by_name,
  1,  netmsg__ping_pong__number_ranges,
  (ProtobufCMessageInit) netmsg__ping_pong__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor netmsg__req_login__field_descriptors[2] =
{
  {
    "userName",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Netmsg__ReqLogin, username),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "psw",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Netmsg__ReqLogin, psw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned netmsg__req_login__field_indices_by_name[] = {
  1,   /* field[1] = psw */
  0,   /* field[0] = userName */
};
static const ProtobufCIntRange netmsg__req_login__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor netmsg__req_login__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "netmsg.ReqLogin",
  "ReqLogin",
  "Netmsg__ReqLogin",
  "netmsg",
  sizeof(Netmsg__ReqLogin),
  2,
  netmsg__req_login__field_descriptors,
  netmsg__req_login__field_indices_by_name,
  1,  netmsg__req_login__number_ranges,
  (ProtobufCMessageInit) netmsg__req_login__init,
  NULL,NULL,NULL    /* reserved[123] */
};
