/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: login.proto */

#ifndef PROTOBUF_C_login_2eproto__INCLUDED
#define PROTOBUF_C_login_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Netmsg__EmptyMsg Netmsg__EmptyMsg;
typedef struct Netmsg__EmptyMsg netmsg__empty_msg;
typedef struct Netmsg__PingPong Netmsg__PingPong;
typedef struct Netmsg__PingPong netmsg__ping_pong;
typedef struct Netmsg__ReqLogin Netmsg__ReqLogin;
typedef struct Netmsg__ReqLogin netmsg__req_login;


/* --- enums --- */


/* --- messages --- */

struct  Netmsg__EmptyMsg
{
  ProtobufCMessage base;
};
#define NETMSG__EMPTY_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&netmsg__empty_msg__descriptor) \
 }


struct  Netmsg__PingPong
{
  ProtobufCMessage base;
  uint32_t time;
};
#define NETMSG__PING_PONG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&netmsg__ping_pong__descriptor) \
, 0 }


struct  Netmsg__ReqLogin
{
  ProtobufCMessage base;
  char *username;
  ProtobufCBinaryData psw;
};
#define NETMSG__REQ_LOGIN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&netmsg__req_login__descriptor) \
, (char *)protobuf_c_empty_string, {0,NULL} }


/* Netmsg__EmptyMsg methods */
void   netmsg__empty_msg__init
                     (Netmsg__EmptyMsg         *message);
size_t netmsg__empty_msg__get_packed_size
                     (const Netmsg__EmptyMsg   *message);
size_t netmsg__empty_msg__pack
                     (const Netmsg__EmptyMsg   *message,
                      uint8_t             *out);
size_t netmsg__empty_msg__pack_to_buffer
                     (const Netmsg__EmptyMsg   *message,
                      ProtobufCBuffer     *buffer);
Netmsg__EmptyMsg *
       netmsg__empty_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   netmsg__empty_msg__free_unpacked
                     (Netmsg__EmptyMsg *message,
                      ProtobufCAllocator *allocator);
/* Netmsg__PingPong methods */
void   netmsg__ping_pong__init
                     (Netmsg__PingPong         *message);
size_t netmsg__ping_pong__get_packed_size
                     (const Netmsg__PingPong   *message);
size_t netmsg__ping_pong__pack
                     (const Netmsg__PingPong   *message,
                      uint8_t             *out);
size_t netmsg__ping_pong__pack_to_buffer
                     (const Netmsg__PingPong   *message,
                      ProtobufCBuffer     *buffer);
Netmsg__PingPong *
       netmsg__ping_pong__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   netmsg__ping_pong__free_unpacked
                     (Netmsg__PingPong *message,
                      ProtobufCAllocator *allocator);
/* Netmsg__ReqLogin methods */
void   netmsg__req_login__init
                     (Netmsg__ReqLogin         *message);
size_t netmsg__req_login__get_packed_size
                     (const Netmsg__ReqLogin   *message);
size_t netmsg__req_login__pack
                     (const Netmsg__ReqLogin   *message,
                      uint8_t             *out);
size_t netmsg__req_login__pack_to_buffer
                     (const Netmsg__ReqLogin   *message,
                      ProtobufCBuffer     *buffer);
Netmsg__ReqLogin *
       netmsg__req_login__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   netmsg__req_login__free_unpacked
                     (Netmsg__ReqLogin *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Netmsg__EmptyMsg_Closure)
                 (const Netmsg__EmptyMsg *message,
                  void *closure_data);
typedef void (*Netmsg__PingPong_Closure)
                 (const Netmsg__PingPong *message,
                  void *closure_data);
typedef void (*Netmsg__ReqLogin_Closure)
                 (const Netmsg__ReqLogin *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor netmsg__empty_msg__descriptor;
extern const ProtobufCMessageDescriptor netmsg__ping_pong__descriptor;
extern const ProtobufCMessageDescriptor netmsg__req_login__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_login_2eproto__INCLUDED */
