// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: login.proto
// Protobuf C++ Version: 5.28.0

#include "login.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace netmsg {

inline constexpr pbSysInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : uniqueid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        devicemodel_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        os_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        runtimeplatform_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR pbSysInfo::pbSysInfo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct pbSysInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR pbSysInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~pbSysInfoDefaultTypeInternal() {}
  union {
    pbSysInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 pbSysInfoDefaultTypeInternal _pbSysInfo_default_instance_;

inline constexpr pbRspReg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : result_{static_cast< ::netmsg::EUserErrorType >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR pbRspReg::pbRspReg(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct pbRspRegDefaultTypeInternal {
  PROTOBUF_CONSTEXPR pbRspRegDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~pbRspRegDefaultTypeInternal() {}
  union {
    pbRspReg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 pbRspRegDefaultTypeInternal _pbRspReg_default_instance_;

inline constexpr pbRspLogin::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : verifykey_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        account_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        userid_{::uint64_t{0u}},
        result_{static_cast< ::netmsg::EUserErrorType >(0)},
        bantime_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR pbRspLogin::pbRspLogin(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct pbRspLoginDefaultTypeInternal {
  PROTOBUF_CONSTEXPR pbRspLoginDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~pbRspLoginDefaultTypeInternal() {}
  union {
    pbRspLogin _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 pbRspLoginDefaultTypeInternal _pbRspLogin_default_instance_;

inline constexpr pbReqReg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : username_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        psw_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        channel_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR pbReqReg::pbReqReg(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct pbReqRegDefaultTypeInternal {
  PROTOBUF_CONSTEXPR pbReqRegDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~pbReqRegDefaultTypeInternal() {}
  union {
    pbReqReg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 pbReqRegDefaultTypeInternal _pbReqReg_default_instance_;

inline constexpr pbPingPong::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : time_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR pbPingPong::pbPingPong(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct pbPingPongDefaultTypeInternal {
  PROTOBUF_CONSTEXPR pbPingPongDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~pbPingPongDefaultTypeInternal() {}
  union {
    pbPingPong _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 pbPingPongDefaultTypeInternal _pbPingPong_default_instance_;

inline constexpr pbReqLogin::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        username_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        psw_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        extdata_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        sysinfodata_{nullptr},
        usertype_{static_cast< ::netmsg::EUserType >(0)},
        channeltype_{static_cast< ::netmsg::EChannelType >(0)},
        version_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR pbReqLogin::pbReqLogin(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct pbReqLoginDefaultTypeInternal {
  PROTOBUF_CONSTEXPR pbReqLoginDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~pbReqLoginDefaultTypeInternal() {}
  union {
    pbReqLogin _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 pbReqLoginDefaultTypeInternal _pbReqLogin_default_instance_;
}  // namespace netmsg
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_login_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_login_2eproto = nullptr;
const ::uint32_t
    TableStruct_login_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::netmsg::pbPingPong, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::netmsg::pbPingPong, _impl_.time_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::netmsg::pbReqReg, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::netmsg::pbReqReg, _impl_.username_),
        PROTOBUF_FIELD_OFFSET(::netmsg::pbReqReg, _impl_.psw_),
        PROTOBUF_FIELD_OFFSET(::netmsg::pbReqReg, _impl_.channel_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::netmsg::pbRspReg, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::netmsg::pbRspReg, _impl_.result_),
        PROTOBUF_FIELD_OFFSET(::netmsg::pbReqLogin, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::netmsg::pbReqLogin, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::netmsg::pbReqLogin, _impl_.username_),
        PROTOBUF_FIELD_OFFSET(::netmsg::pbReqLogin, _impl_.psw_),
        PROTOBUF_FIELD_OFFSET(::netmsg::pbReqLogin, _impl_.usertype_),
        PROTOBUF_FIELD_OFFSET(::netmsg::pbReqLogin, _impl_.channeltype_),
        PROTOBUF_FIELD_OFFSET(::netmsg::pbReqLogin, _impl_.version_),
        PROTOBUF_FIELD_OFFSET(::netmsg::pbReqLogin, _impl_.sysinfodata_),
        PROTOBUF_FIELD_OFFSET(::netmsg::pbReqLogin, _impl_.extdata_),
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        0,
        ~0u,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::netmsg::pbRspLogin, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::netmsg::pbRspLogin, _impl_.result_),
        PROTOBUF_FIELD_OFFSET(::netmsg::pbRspLogin, _impl_.userid_),
        PROTOBUF_FIELD_OFFSET(::netmsg::pbRspLogin, _impl_.bantime_),
        PROTOBUF_FIELD_OFFSET(::netmsg::pbRspLogin, _impl_.verifykey_),
        PROTOBUF_FIELD_OFFSET(::netmsg::pbRspLogin, _impl_.account_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::netmsg::pbSysInfo, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::netmsg::pbSysInfo, _impl_.runtimeplatform_),
        PROTOBUF_FIELD_OFFSET(::netmsg::pbSysInfo, _impl_.uniqueid_),
        PROTOBUF_FIELD_OFFSET(::netmsg::pbSysInfo, _impl_.devicemodel_),
        PROTOBUF_FIELD_OFFSET(::netmsg::pbSysInfo, _impl_.os_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::netmsg::pbPingPong)},
        {9, -1, -1, sizeof(::netmsg::pbReqReg)},
        {20, -1, -1, sizeof(::netmsg::pbRspReg)},
        {29, 44, -1, sizeof(::netmsg::pbReqLogin)},
        {51, -1, -1, sizeof(::netmsg::pbRspLogin)},
        {64, -1, -1, sizeof(::netmsg::pbSysInfo)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::netmsg::_pbPingPong_default_instance_._instance,
    &::netmsg::_pbReqReg_default_instance_._instance,
    &::netmsg::_pbRspReg_default_instance_._instance,
    &::netmsg::_pbReqLogin_default_instance_._instance,
    &::netmsg::_pbRspLogin_default_instance_._instance,
    &::netmsg::_pbSysInfo_default_instance_._instance,
};
const char descriptor_table_protodef_login_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013login.proto\022\006netmsg\032\013enums.proto\"\032\n\npb"
    "PingPong\022\014\n\004time\030\001 \001(\r\":\n\010pbReqReg\022\020\n\010us"
    "erName\030\001 \001(\t\022\013\n\003psw\030\002 \001(\014\022\017\n\007channel\030\003 \001"
    "(\t\"2\n\010pbRspReg\022&\n\006result\030\001 \001(\0162\026.netmsg."
    "EUserErrorType\"\305\001\n\npbReqLogin\022\020\n\010userNam"
    "e\030\001 \001(\t\022\013\n\003psw\030\002 \001(\014\022#\n\010userType\030\003 \001(\0162\021"
    ".netmsg.EUserType\022)\n\013channelType\030\004 \001(\0162\024"
    ".netmsg.EChannelType\022\017\n\007version\030\005 \001(\r\022&\n"
    "\013sysInfoData\030\006 \001(\0132\021.netmsg.pbSysInfo\022\017\n"
    "\007ExtData\030\007 \001(\t\"y\n\npbRspLogin\022&\n\006result\030\001"
    " \001(\0162\026.netmsg.EUserErrorType\022\016\n\006userId\030\002"
    " \001(\004\022\017\n\007banTime\030\003 \001(\r\022\021\n\tverifyKey\030\004 \001(\t"
    "\022\017\n\007account\030\005 \001(\t\"W\n\tpbSysInfo\022\027\n\017Runtim"
    "ePlatform\030\001 \001(\r\022\020\n\010UniqueId\030\002 \001(\t\022\023\n\013Dev"
    "iceModel\030\003 \001(\t\022\n\n\002OS\030\004 \001(\tb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_login_2eproto_deps[1] =
    {
        &::descriptor_table_enums_2eproto,
};
static ::absl::once_flag descriptor_table_login_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_login_2eproto = {
    false,
    false,
    594,
    descriptor_table_protodef_login_2eproto,
    "login.proto",
    &descriptor_table_login_2eproto_once,
    descriptor_table_login_2eproto_deps,
    1,
    6,
    schemas,
    file_default_instances,
    TableStruct_login_2eproto::offsets,
    file_level_enum_descriptors_login_2eproto,
    file_level_service_descriptors_login_2eproto,
};
namespace netmsg {
// ===================================================================

class pbPingPong::_Internal {
 public:
};

pbPingPong::pbPingPong(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:netmsg.pbPingPong)
}
pbPingPong::pbPingPong(
    ::google::protobuf::Arena* arena, const pbPingPong& from)
    : pbPingPong(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE pbPingPong::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void pbPingPong::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.time_ = {};
}
pbPingPong::~pbPingPong() {
  // @@protoc_insertion_point(destructor:netmsg.pbPingPong)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void pbPingPong::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    pbPingPong::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_pbPingPong_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &pbPingPong::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<pbPingPong>(),
            ::google::protobuf::Message::GetNewImpl<pbPingPong>(),
            ::google::protobuf::Message::GetClearImpl<pbPingPong>(), &pbPingPong::ByteSizeLong,
                &pbPingPong::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(pbPingPong, _impl_._cached_size_),
            false,
        },
        &pbPingPong::kDescriptorMethods,
        &descriptor_table_login_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* pbPingPong::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> pbPingPong::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::netmsg::pbPingPong>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 time = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(pbPingPong, _impl_.time_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(pbPingPong, _impl_.time_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 time = 1;
    {PROTOBUF_FIELD_OFFSET(pbPingPong, _impl_.time_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void pbPingPong::Clear() {
// @@protoc_insertion_point(message_clear_start:netmsg.pbPingPong)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.time_ = 0u;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* pbPingPong::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const pbPingPong& this_ = static_cast<const pbPingPong&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* pbPingPong::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const pbPingPong& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:netmsg.pbPingPong)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 time = 1;
          if (this_._internal_time() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_time(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:netmsg.pbPingPong)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t pbPingPong::ByteSizeLong(const MessageLite& base) {
          const pbPingPong& this_ = static_cast<const pbPingPong&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t pbPingPong::ByteSizeLong() const {
          const pbPingPong& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:netmsg.pbPingPong)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // uint32 time = 1;
            if (this_._internal_time() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_time());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void pbPingPong::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<pbPingPong*>(&to_msg);
  auto& from = static_cast<const pbPingPong&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:netmsg.pbPingPong)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_time() != 0) {
    _this->_impl_.time_ = from._impl_.time_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void pbPingPong::CopyFrom(const pbPingPong& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:netmsg.pbPingPong)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void pbPingPong::InternalSwap(pbPingPong* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.time_, other->_impl_.time_);
}

::google::protobuf::Metadata pbPingPong::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class pbReqReg::_Internal {
 public:
};

pbReqReg::pbReqReg(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:netmsg.pbReqReg)
}
inline PROTOBUF_NDEBUG_INLINE pbReqReg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::netmsg::pbReqReg& from_msg)
      : username_(arena, from.username_),
        psw_(arena, from.psw_),
        channel_(arena, from.channel_),
        _cached_size_{0} {}

pbReqReg::pbReqReg(
    ::google::protobuf::Arena* arena,
    const pbReqReg& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  pbReqReg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:netmsg.pbReqReg)
}
inline PROTOBUF_NDEBUG_INLINE pbReqReg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : username_(arena),
        psw_(arena),
        channel_(arena),
        _cached_size_{0} {}

inline void pbReqReg::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
pbReqReg::~pbReqReg() {
  // @@protoc_insertion_point(destructor:netmsg.pbReqReg)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void pbReqReg::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.username_.Destroy();
  _impl_.psw_.Destroy();
  _impl_.channel_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    pbReqReg::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_pbReqReg_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &pbReqReg::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<pbReqReg>(),
            ::google::protobuf::Message::GetNewImpl<pbReqReg>(),
            ::google::protobuf::Message::GetClearImpl<pbReqReg>(), &pbReqReg::ByteSizeLong,
                &pbReqReg::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(pbReqReg, _impl_._cached_size_),
            false,
        },
        &pbReqReg::kDescriptorMethods,
        &descriptor_table_login_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* pbReqReg::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 39, 2> pbReqReg::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::netmsg::pbReqReg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string userName = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(pbReqReg, _impl_.username_)}},
    // bytes psw = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(pbReqReg, _impl_.psw_)}},
    // string channel = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(pbReqReg, _impl_.channel_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string userName = 1;
    {PROTOBUF_FIELD_OFFSET(pbReqReg, _impl_.username_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes psw = 2;
    {PROTOBUF_FIELD_OFFSET(pbReqReg, _impl_.psw_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // string channel = 3;
    {PROTOBUF_FIELD_OFFSET(pbReqReg, _impl_.channel_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\17\10\0\7\0\0\0\0"
    "netmsg.pbReqReg"
    "userName"
    "channel"
  }},
};

PROTOBUF_NOINLINE void pbReqReg::Clear() {
// @@protoc_insertion_point(message_clear_start:netmsg.pbReqReg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.username_.ClearToEmpty();
  _impl_.psw_.ClearToEmpty();
  _impl_.channel_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* pbReqReg::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const pbReqReg& this_ = static_cast<const pbReqReg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* pbReqReg::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const pbReqReg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:netmsg.pbReqReg)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string userName = 1;
          if (!this_._internal_username().empty()) {
            const std::string& _s = this_._internal_username();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "netmsg.pbReqReg.userName");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // bytes psw = 2;
          if (!this_._internal_psw().empty()) {
            const std::string& _s = this_._internal_psw();
            target = stream->WriteBytesMaybeAliased(2, _s, target);
          }

          // string channel = 3;
          if (!this_._internal_channel().empty()) {
            const std::string& _s = this_._internal_channel();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "netmsg.pbReqReg.channel");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:netmsg.pbReqReg)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t pbReqReg::ByteSizeLong(const MessageLite& base) {
          const pbReqReg& this_ = static_cast<const pbReqReg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t pbReqReg::ByteSizeLong() const {
          const pbReqReg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:netmsg.pbReqReg)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string userName = 1;
            if (!this_._internal_username().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_username());
            }
            // bytes psw = 2;
            if (!this_._internal_psw().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_psw());
            }
            // string channel = 3;
            if (!this_._internal_channel().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_channel());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void pbReqReg::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<pbReqReg*>(&to_msg);
  auto& from = static_cast<const pbReqReg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:netmsg.pbReqReg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_username().empty()) {
    _this->_internal_set_username(from._internal_username());
  }
  if (!from._internal_psw().empty()) {
    _this->_internal_set_psw(from._internal_psw());
  }
  if (!from._internal_channel().empty()) {
    _this->_internal_set_channel(from._internal_channel());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void pbReqReg::CopyFrom(const pbReqReg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:netmsg.pbReqReg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void pbReqReg::InternalSwap(pbReqReg* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.username_, &other->_impl_.username_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.psw_, &other->_impl_.psw_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.channel_, &other->_impl_.channel_, arena);
}

::google::protobuf::Metadata pbReqReg::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class pbRspReg::_Internal {
 public:
};

pbRspReg::pbRspReg(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:netmsg.pbRspReg)
}
pbRspReg::pbRspReg(
    ::google::protobuf::Arena* arena, const pbRspReg& from)
    : pbRspReg(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE pbRspReg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void pbRspReg::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.result_ = {};
}
pbRspReg::~pbRspReg() {
  // @@protoc_insertion_point(destructor:netmsg.pbRspReg)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void pbRspReg::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    pbRspReg::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_pbRspReg_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &pbRspReg::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<pbRspReg>(),
            ::google::protobuf::Message::GetNewImpl<pbRspReg>(),
            ::google::protobuf::Message::GetClearImpl<pbRspReg>(), &pbRspReg::ByteSizeLong,
                &pbRspReg::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(pbRspReg, _impl_._cached_size_),
            false,
        },
        &pbRspReg::kDescriptorMethods,
        &descriptor_table_login_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* pbRspReg::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> pbRspReg::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::netmsg::pbRspReg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .netmsg.EUserErrorType result = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(pbRspReg, _impl_.result_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(pbRspReg, _impl_.result_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .netmsg.EUserErrorType result = 1;
    {PROTOBUF_FIELD_OFFSET(pbRspReg, _impl_.result_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void pbRspReg::Clear() {
// @@protoc_insertion_point(message_clear_start:netmsg.pbRspReg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* pbRspReg::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const pbRspReg& this_ = static_cast<const pbRspReg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* pbRspReg::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const pbRspReg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:netmsg.pbRspReg)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .netmsg.EUserErrorType result = 1;
          if (this_._internal_result() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_result(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:netmsg.pbRspReg)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t pbRspReg::ByteSizeLong(const MessageLite& base) {
          const pbRspReg& this_ = static_cast<const pbRspReg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t pbRspReg::ByteSizeLong() const {
          const pbRspReg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:netmsg.pbRspReg)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // .netmsg.EUserErrorType result = 1;
            if (this_._internal_result() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_result());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void pbRspReg::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<pbRspReg*>(&to_msg);
  auto& from = static_cast<const pbRspReg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:netmsg.pbRspReg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_result() != 0) {
    _this->_impl_.result_ = from._impl_.result_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void pbRspReg::CopyFrom(const pbRspReg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:netmsg.pbRspReg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void pbRspReg::InternalSwap(pbRspReg* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.result_, other->_impl_.result_);
}

::google::protobuf::Metadata pbRspReg::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class pbReqLogin::_Internal {
 public:
  using HasBits =
      decltype(std::declval<pbReqLogin>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(pbReqLogin, _impl_._has_bits_);
};

pbReqLogin::pbReqLogin(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:netmsg.pbReqLogin)
}
inline PROTOBUF_NDEBUG_INLINE pbReqLogin::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::netmsg::pbReqLogin& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        username_(arena, from.username_),
        psw_(arena, from.psw_),
        extdata_(arena, from.extdata_) {}

pbReqLogin::pbReqLogin(
    ::google::protobuf::Arena* arena,
    const pbReqLogin& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  pbReqLogin* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.sysinfodata_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::netmsg::pbSysInfo>(
                              arena, *from._impl_.sysinfodata_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, usertype_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, usertype_),
           offsetof(Impl_, version_) -
               offsetof(Impl_, usertype_) +
               sizeof(Impl_::version_));

  // @@protoc_insertion_point(copy_constructor:netmsg.pbReqLogin)
}
inline PROTOBUF_NDEBUG_INLINE pbReqLogin::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        username_(arena),
        psw_(arena),
        extdata_(arena) {}

inline void pbReqLogin::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, sysinfodata_),
           0,
           offsetof(Impl_, version_) -
               offsetof(Impl_, sysinfodata_) +
               sizeof(Impl_::version_));
}
pbReqLogin::~pbReqLogin() {
  // @@protoc_insertion_point(destructor:netmsg.pbReqLogin)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void pbReqLogin::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.username_.Destroy();
  _impl_.psw_.Destroy();
  _impl_.extdata_.Destroy();
  delete _impl_.sysinfodata_;
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    pbReqLogin::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_pbReqLogin_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &pbReqLogin::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<pbReqLogin>(),
            ::google::protobuf::Message::GetNewImpl<pbReqLogin>(),
            ::google::protobuf::Message::GetClearImpl<pbReqLogin>(), &pbReqLogin::ByteSizeLong,
                &pbReqLogin::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(pbReqLogin, _impl_._cached_size_),
            false,
        },
        &pbReqLogin::kDescriptorMethods,
        &descriptor_table_login_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* pbReqLogin::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 1, 41, 2> pbReqLogin::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(pbReqLogin, _impl_._has_bits_),
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::netmsg::pbReqLogin>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string userName = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(pbReqLogin, _impl_.username_)}},
    // bytes psw = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(pbReqLogin, _impl_.psw_)}},
    // .netmsg.EUserType userType = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(pbReqLogin, _impl_.usertype_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(pbReqLogin, _impl_.usertype_)}},
    // .netmsg.EChannelType channelType = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(pbReqLogin, _impl_.channeltype_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(pbReqLogin, _impl_.channeltype_)}},
    // uint32 version = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(pbReqLogin, _impl_.version_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(pbReqLogin, _impl_.version_)}},
    // .netmsg.pbSysInfo sysInfoData = 6;
    {::_pbi::TcParser::FastMtS1,
     {50, 0, 0, PROTOBUF_FIELD_OFFSET(pbReqLogin, _impl_.sysinfodata_)}},
    // string ExtData = 7;
    {::_pbi::TcParser::FastUS1,
     {58, 63, 0, PROTOBUF_FIELD_OFFSET(pbReqLogin, _impl_.extdata_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string userName = 1;
    {PROTOBUF_FIELD_OFFSET(pbReqLogin, _impl_.username_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes psw = 2;
    {PROTOBUF_FIELD_OFFSET(pbReqLogin, _impl_.psw_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // .netmsg.EUserType userType = 3;
    {PROTOBUF_FIELD_OFFSET(pbReqLogin, _impl_.usertype_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .netmsg.EChannelType channelType = 4;
    {PROTOBUF_FIELD_OFFSET(pbReqLogin, _impl_.channeltype_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // uint32 version = 5;
    {PROTOBUF_FIELD_OFFSET(pbReqLogin, _impl_.version_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // .netmsg.pbSysInfo sysInfoData = 6;
    {PROTOBUF_FIELD_OFFSET(pbReqLogin, _impl_.sysinfodata_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string ExtData = 7;
    {PROTOBUF_FIELD_OFFSET(pbReqLogin, _impl_.extdata_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }}, {{
    {::_pbi::TcParser::GetTable<::netmsg::pbSysInfo>()},
  }}, {{
    "\21\10\0\0\0\0\0\7"
    "netmsg.pbReqLogin"
    "userName"
    "ExtData"
  }},
};

PROTOBUF_NOINLINE void pbReqLogin::Clear() {
// @@protoc_insertion_point(message_clear_start:netmsg.pbReqLogin)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.username_.ClearToEmpty();
  _impl_.psw_.ClearToEmpty();
  _impl_.extdata_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.sysinfodata_ != nullptr);
    _impl_.sysinfodata_->Clear();
  }
  ::memset(&_impl_.usertype_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.version_) -
      reinterpret_cast<char*>(&_impl_.usertype_)) + sizeof(_impl_.version_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* pbReqLogin::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const pbReqLogin& this_ = static_cast<const pbReqLogin&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* pbReqLogin::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const pbReqLogin& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:netmsg.pbReqLogin)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string userName = 1;
          if (!this_._internal_username().empty()) {
            const std::string& _s = this_._internal_username();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "netmsg.pbReqLogin.userName");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // bytes psw = 2;
          if (!this_._internal_psw().empty()) {
            const std::string& _s = this_._internal_psw();
            target = stream->WriteBytesMaybeAliased(2, _s, target);
          }

          // .netmsg.EUserType userType = 3;
          if (this_._internal_usertype() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                3, this_._internal_usertype(), target);
          }

          // .netmsg.EChannelType channelType = 4;
          if (this_._internal_channeltype() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                4, this_._internal_channeltype(), target);
          }

          // uint32 version = 5;
          if (this_._internal_version() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                5, this_._internal_version(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .netmsg.pbSysInfo sysInfoData = 6;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                6, *this_._impl_.sysinfodata_, this_._impl_.sysinfodata_->GetCachedSize(), target,
                stream);
          }

          // string ExtData = 7;
          if (!this_._internal_extdata().empty()) {
            const std::string& _s = this_._internal_extdata();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "netmsg.pbReqLogin.ExtData");
            target = stream->WriteStringMaybeAliased(7, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:netmsg.pbReqLogin)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t pbReqLogin::ByteSizeLong(const MessageLite& base) {
          const pbReqLogin& this_ = static_cast<const pbReqLogin&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t pbReqLogin::ByteSizeLong() const {
          const pbReqLogin& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:netmsg.pbReqLogin)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string userName = 1;
            if (!this_._internal_username().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_username());
            }
            // bytes psw = 2;
            if (!this_._internal_psw().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_psw());
            }
            // string ExtData = 7;
            if (!this_._internal_extdata().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_extdata());
            }
          }
           {
            // .netmsg.pbSysInfo sysInfoData = 6;
            cached_has_bits =
                this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.sysinfodata_);
            }
          }
           {
            // .netmsg.EUserType userType = 3;
            if (this_._internal_usertype() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_usertype());
            }
            // .netmsg.EChannelType channelType = 4;
            if (this_._internal_channeltype() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_channeltype());
            }
            // uint32 version = 5;
            if (this_._internal_version() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_version());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void pbReqLogin::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<pbReqLogin*>(&to_msg);
  auto& from = static_cast<const pbReqLogin&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:netmsg.pbReqLogin)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_username().empty()) {
    _this->_internal_set_username(from._internal_username());
  }
  if (!from._internal_psw().empty()) {
    _this->_internal_set_psw(from._internal_psw());
  }
  if (!from._internal_extdata().empty()) {
    _this->_internal_set_extdata(from._internal_extdata());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.sysinfodata_ != nullptr);
    if (_this->_impl_.sysinfodata_ == nullptr) {
      _this->_impl_.sysinfodata_ =
          ::google::protobuf::Message::CopyConstruct<::netmsg::pbSysInfo>(arena, *from._impl_.sysinfodata_);
    } else {
      _this->_impl_.sysinfodata_->MergeFrom(*from._impl_.sysinfodata_);
    }
  }
  if (from._internal_usertype() != 0) {
    _this->_impl_.usertype_ = from._impl_.usertype_;
  }
  if (from._internal_channeltype() != 0) {
    _this->_impl_.channeltype_ = from._impl_.channeltype_;
  }
  if (from._internal_version() != 0) {
    _this->_impl_.version_ = from._impl_.version_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void pbReqLogin::CopyFrom(const pbReqLogin& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:netmsg.pbReqLogin)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void pbReqLogin::InternalSwap(pbReqLogin* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.username_, &other->_impl_.username_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.psw_, &other->_impl_.psw_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.extdata_, &other->_impl_.extdata_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(pbReqLogin, _impl_.version_)
      + sizeof(pbReqLogin::_impl_.version_)
      - PROTOBUF_FIELD_OFFSET(pbReqLogin, _impl_.sysinfodata_)>(
          reinterpret_cast<char*>(&_impl_.sysinfodata_),
          reinterpret_cast<char*>(&other->_impl_.sysinfodata_));
}

::google::protobuf::Metadata pbReqLogin::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class pbRspLogin::_Internal {
 public:
};

pbRspLogin::pbRspLogin(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:netmsg.pbRspLogin)
}
inline PROTOBUF_NDEBUG_INLINE pbRspLogin::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::netmsg::pbRspLogin& from_msg)
      : verifykey_(arena, from.verifykey_),
        account_(arena, from.account_),
        _cached_size_{0} {}

pbRspLogin::pbRspLogin(
    ::google::protobuf::Arena* arena,
    const pbRspLogin& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  pbRspLogin* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, userid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, userid_),
           offsetof(Impl_, bantime_) -
               offsetof(Impl_, userid_) +
               sizeof(Impl_::bantime_));

  // @@protoc_insertion_point(copy_constructor:netmsg.pbRspLogin)
}
inline PROTOBUF_NDEBUG_INLINE pbRspLogin::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : verifykey_(arena),
        account_(arena),
        _cached_size_{0} {}

inline void pbRspLogin::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, userid_),
           0,
           offsetof(Impl_, bantime_) -
               offsetof(Impl_, userid_) +
               sizeof(Impl_::bantime_));
}
pbRspLogin::~pbRspLogin() {
  // @@protoc_insertion_point(destructor:netmsg.pbRspLogin)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void pbRspLogin::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.verifykey_.Destroy();
  _impl_.account_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    pbRspLogin::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_pbRspLogin_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &pbRspLogin::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<pbRspLogin>(),
            ::google::protobuf::Message::GetNewImpl<pbRspLogin>(),
            ::google::protobuf::Message::GetClearImpl<pbRspLogin>(), &pbRspLogin::ByteSizeLong,
                &pbRspLogin::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(pbRspLogin, _impl_._cached_size_),
            false,
        },
        &pbRspLogin::kDescriptorMethods,
        &descriptor_table_login_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* pbRspLogin::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 42, 2> pbRspLogin::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::netmsg::pbRspLogin>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .netmsg.EUserErrorType result = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(pbRspLogin, _impl_.result_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(pbRspLogin, _impl_.result_)}},
    // uint64 userId = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(pbRspLogin, _impl_.userid_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(pbRspLogin, _impl_.userid_)}},
    // uint32 banTime = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(pbRspLogin, _impl_.bantime_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(pbRspLogin, _impl_.bantime_)}},
    // string verifyKey = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(pbRspLogin, _impl_.verifykey_)}},
    // string account = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(pbRspLogin, _impl_.account_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .netmsg.EUserErrorType result = 1;
    {PROTOBUF_FIELD_OFFSET(pbRspLogin, _impl_.result_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // uint64 userId = 2;
    {PROTOBUF_FIELD_OFFSET(pbRspLogin, _impl_.userid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint32 banTime = 3;
    {PROTOBUF_FIELD_OFFSET(pbRspLogin, _impl_.bantime_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // string verifyKey = 4;
    {PROTOBUF_FIELD_OFFSET(pbRspLogin, _impl_.verifykey_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string account = 5;
    {PROTOBUF_FIELD_OFFSET(pbRspLogin, _impl_.account_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\21\0\0\0\11\7\0\0"
    "netmsg.pbRspLogin"
    "verifyKey"
    "account"
  }},
};

PROTOBUF_NOINLINE void pbRspLogin::Clear() {
// @@protoc_insertion_point(message_clear_start:netmsg.pbRspLogin)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.verifykey_.ClearToEmpty();
  _impl_.account_.ClearToEmpty();
  ::memset(&_impl_.userid_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.bantime_) -
      reinterpret_cast<char*>(&_impl_.userid_)) + sizeof(_impl_.bantime_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* pbRspLogin::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const pbRspLogin& this_ = static_cast<const pbRspLogin&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* pbRspLogin::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const pbRspLogin& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:netmsg.pbRspLogin)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .netmsg.EUserErrorType result = 1;
          if (this_._internal_result() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_result(), target);
          }

          // uint64 userId = 2;
          if (this_._internal_userid() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                2, this_._internal_userid(), target);
          }

          // uint32 banTime = 3;
          if (this_._internal_bantime() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                3, this_._internal_bantime(), target);
          }

          // string verifyKey = 4;
          if (!this_._internal_verifykey().empty()) {
            const std::string& _s = this_._internal_verifykey();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "netmsg.pbRspLogin.verifyKey");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          // string account = 5;
          if (!this_._internal_account().empty()) {
            const std::string& _s = this_._internal_account();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "netmsg.pbRspLogin.account");
            target = stream->WriteStringMaybeAliased(5, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:netmsg.pbRspLogin)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t pbRspLogin::ByteSizeLong(const MessageLite& base) {
          const pbRspLogin& this_ = static_cast<const pbRspLogin&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t pbRspLogin::ByteSizeLong() const {
          const pbRspLogin& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:netmsg.pbRspLogin)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string verifyKey = 4;
            if (!this_._internal_verifykey().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_verifykey());
            }
            // string account = 5;
            if (!this_._internal_account().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_account());
            }
            // uint64 userId = 2;
            if (this_._internal_userid() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_userid());
            }
            // .netmsg.EUserErrorType result = 1;
            if (this_._internal_result() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_result());
            }
            // uint32 banTime = 3;
            if (this_._internal_bantime() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_bantime());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void pbRspLogin::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<pbRspLogin*>(&to_msg);
  auto& from = static_cast<const pbRspLogin&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:netmsg.pbRspLogin)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_verifykey().empty()) {
    _this->_internal_set_verifykey(from._internal_verifykey());
  }
  if (!from._internal_account().empty()) {
    _this->_internal_set_account(from._internal_account());
  }
  if (from._internal_userid() != 0) {
    _this->_impl_.userid_ = from._impl_.userid_;
  }
  if (from._internal_result() != 0) {
    _this->_impl_.result_ = from._impl_.result_;
  }
  if (from._internal_bantime() != 0) {
    _this->_impl_.bantime_ = from._impl_.bantime_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void pbRspLogin::CopyFrom(const pbRspLogin& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:netmsg.pbRspLogin)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void pbRspLogin::InternalSwap(pbRspLogin* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.verifykey_, &other->_impl_.verifykey_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.account_, &other->_impl_.account_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(pbRspLogin, _impl_.bantime_)
      + sizeof(pbRspLogin::_impl_.bantime_)
      - PROTOBUF_FIELD_OFFSET(pbRspLogin, _impl_.userid_)>(
          reinterpret_cast<char*>(&_impl_.userid_),
          reinterpret_cast<char*>(&other->_impl_.userid_));
}

::google::protobuf::Metadata pbRspLogin::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class pbSysInfo::_Internal {
 public:
};

pbSysInfo::pbSysInfo(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:netmsg.pbSysInfo)
}
inline PROTOBUF_NDEBUG_INLINE pbSysInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::netmsg::pbSysInfo& from_msg)
      : uniqueid_(arena, from.uniqueid_),
        devicemodel_(arena, from.devicemodel_),
        os_(arena, from.os_),
        _cached_size_{0} {}

pbSysInfo::pbSysInfo(
    ::google::protobuf::Arena* arena,
    const pbSysInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  pbSysInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.runtimeplatform_ = from._impl_.runtimeplatform_;

  // @@protoc_insertion_point(copy_constructor:netmsg.pbSysInfo)
}
inline PROTOBUF_NDEBUG_INLINE pbSysInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : uniqueid_(arena),
        devicemodel_(arena),
        os_(arena),
        _cached_size_{0} {}

inline void pbSysInfo::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.runtimeplatform_ = {};
}
pbSysInfo::~pbSysInfo() {
  // @@protoc_insertion_point(destructor:netmsg.pbSysInfo)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void pbSysInfo::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.uniqueid_.Destroy();
  _impl_.devicemodel_.Destroy();
  _impl_.os_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    pbSysInfo::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_pbSysInfo_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &pbSysInfo::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<pbSysInfo>(),
            ::google::protobuf::Message::GetNewImpl<pbSysInfo>(),
            ::google::protobuf::Message::GetClearImpl<pbSysInfo>(), &pbSysInfo::ByteSizeLong,
                &pbSysInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(pbSysInfo, _impl_._cached_size_),
            false,
        },
        &pbSysInfo::kDescriptorMethods,
        &descriptor_table_login_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* pbSysInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 46, 2> pbSysInfo::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::netmsg::pbSysInfo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string OS = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(pbSysInfo, _impl_.os_)}},
    // uint32 RuntimePlatform = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(pbSysInfo, _impl_.runtimeplatform_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(pbSysInfo, _impl_.runtimeplatform_)}},
    // string UniqueId = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(pbSysInfo, _impl_.uniqueid_)}},
    // string DeviceModel = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(pbSysInfo, _impl_.devicemodel_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 RuntimePlatform = 1;
    {PROTOBUF_FIELD_OFFSET(pbSysInfo, _impl_.runtimeplatform_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // string UniqueId = 2;
    {PROTOBUF_FIELD_OFFSET(pbSysInfo, _impl_.uniqueid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string DeviceModel = 3;
    {PROTOBUF_FIELD_OFFSET(pbSysInfo, _impl_.devicemodel_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string OS = 4;
    {PROTOBUF_FIELD_OFFSET(pbSysInfo, _impl_.os_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\20\0\10\13\2\0\0\0"
    "netmsg.pbSysInfo"
    "UniqueId"
    "DeviceModel"
    "OS"
  }},
};

PROTOBUF_NOINLINE void pbSysInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:netmsg.pbSysInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.uniqueid_.ClearToEmpty();
  _impl_.devicemodel_.ClearToEmpty();
  _impl_.os_.ClearToEmpty();
  _impl_.runtimeplatform_ = 0u;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* pbSysInfo::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const pbSysInfo& this_ = static_cast<const pbSysInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* pbSysInfo::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const pbSysInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:netmsg.pbSysInfo)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 RuntimePlatform = 1;
          if (this_._internal_runtimeplatform() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_runtimeplatform(), target);
          }

          // string UniqueId = 2;
          if (!this_._internal_uniqueid().empty()) {
            const std::string& _s = this_._internal_uniqueid();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "netmsg.pbSysInfo.UniqueId");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string DeviceModel = 3;
          if (!this_._internal_devicemodel().empty()) {
            const std::string& _s = this_._internal_devicemodel();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "netmsg.pbSysInfo.DeviceModel");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // string OS = 4;
          if (!this_._internal_os().empty()) {
            const std::string& _s = this_._internal_os();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "netmsg.pbSysInfo.OS");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:netmsg.pbSysInfo)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t pbSysInfo::ByteSizeLong(const MessageLite& base) {
          const pbSysInfo& this_ = static_cast<const pbSysInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t pbSysInfo::ByteSizeLong() const {
          const pbSysInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:netmsg.pbSysInfo)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string UniqueId = 2;
            if (!this_._internal_uniqueid().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_uniqueid());
            }
            // string DeviceModel = 3;
            if (!this_._internal_devicemodel().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_devicemodel());
            }
            // string OS = 4;
            if (!this_._internal_os().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_os());
            }
            // uint32 RuntimePlatform = 1;
            if (this_._internal_runtimeplatform() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_runtimeplatform());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void pbSysInfo::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<pbSysInfo*>(&to_msg);
  auto& from = static_cast<const pbSysInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:netmsg.pbSysInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_uniqueid().empty()) {
    _this->_internal_set_uniqueid(from._internal_uniqueid());
  }
  if (!from._internal_devicemodel().empty()) {
    _this->_internal_set_devicemodel(from._internal_devicemodel());
  }
  if (!from._internal_os().empty()) {
    _this->_internal_set_os(from._internal_os());
  }
  if (from._internal_runtimeplatform() != 0) {
    _this->_impl_.runtimeplatform_ = from._impl_.runtimeplatform_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void pbSysInfo::CopyFrom(const pbSysInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:netmsg.pbSysInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void pbSysInfo::InternalSwap(pbSysInfo* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.uniqueid_, &other->_impl_.uniqueid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.devicemodel_, &other->_impl_.devicemodel_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.os_, &other->_impl_.os_, arena);
        swap(_impl_.runtimeplatform_, other->_impl_.runtimeplatform_);
}

::google::protobuf::Metadata pbSysInfo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace netmsg
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_login_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
