// A simple script to fix the broken fonts in PDF files generated by S22PDF.

if (scriptArgs.length != 2) {
	print("usage: mutool run fix-s22pdf.js input.pdf output.pdf");
	quit();
}

var doc = Document.openDocument(scriptArgs[0]);

var font = new Font("zh-Hans");
var song = doc.addCJKFont(font, "zh-Hans", "H", "serif");
var heiti = doc.addCJKFont(font, "zh-Hans", "H", "sans-serif");
var kaiti = doc.addCJKFont(font, "zh-Hans", "H", "serif");

song.Encoding = 'GBK-EUC-H';
heiti.Encoding = 'GBK-EUC-H';
kaiti.Encoding = 'GBK-EUC-H';

// Key中的十六进制数为汉字的GBK编码
// 比如`#CB#CE#CC#E5`即为`0xCB 0xCE 0xCC 0xE5`，是`宋体`的GBK编码
var MAP = {
	"/#CB#CE#CC#E5": song, // SimSun，宋体使用宋体
	"/#BA#DA#CC#E5": heiti, // SimHei，黑体使用黑体
	"/#BF#AC#CC#E5_GB2312": kaiti, // SimKai，楷体_GB2312使用楷体
	"/#B7#C2#CB#CE_GB2312": song, // SimFang，仿宋使用宋体
	"/#C1#A5#CA#E9": kaiti, // SimLi，隶书使用楷体
}

var i, n = doc.countPages();
for (i = 0; i < n; ++i) {
	var fonts = doc.findPage(i).Resources.Font;
	if (fonts) {
		fonts.forEach(function (font, name) {
			if (font.BaseFont in MAP && font.Encoding == 'WinAnsiEncoding') {
				fonts[name] = MAP[font.BaseFont];
			}
		});
	}
}

doc.save(scriptArgs[1]);
